services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    #volumes:
      #- mongo-data:/data/db
    networks:
      - shared-warehouses

  nats:
     container_name: nats
     image: nats:latest
     ports:
       - "4222:4222"
     command:
       - "--jetstream"
       - "--debug"
       - "--trace"
     networks:
       - shared-warehouses 

  resgate:
    image: resgateio/resgate
    container_name: resgate
    ports:
      - "8080:8080"
    command: >
      -n nats://nats:4222
    depends_on:
      - nats
    networks:
       - shared-warehouses

  mvp-inventory:
    build:
      context: ./microservices/warehouse/inventory
      dockerfile: Dockerfile
    container_name: mvp-inventory-1   
    environment:
      - MONGO_URI=mongodb://mongo:27017/inventory
      - WAREHOUSE_ID=1
      - NATS_URL=nats://nats:4222
    volumes:
      - ./microservices/warehouse/inventory/src:/usr/src/app/src
    networks:
      - shared-warehouses
    depends_on:
      - mongo
      - nats
      - resgate
    

  mvp-inventory-aggregated:
    build:
      context: ./microservices/warehouse/inventory-aggregated
      dockerfile: Dockerfile
    container_name: mvp-inventory-aggregated-1
    environment:
      - MONGO_URI=mongodb://mongo:27017/inventory-aggregated
      - NATS_URL=nats://nats:4222
    volumes:
      - ./microservices/warehouse/inventory-aggregated/src:/usr/src/app/src
    networks:
      - shared-warehouses
    depends_on:
      - mongo
      - nats
      - resgate

networks:
  shared-warehouses:
    driver: bridge