services:

#==========================================================================#
#                         Warehouse Microservices                          #
#==========================================================================#
  inventory:
    build:
      context: ./microservices/warehouse/inventory
      dockerfile: Dockerfile
    container_name: inventory-1
    environment:
      - MONGO_URI=mongodb://mongo:27017/inventory
      - WAREHOUSE_ID=1
      - NATS_URL=nats://nats:4222
    volumes:
      - ./microservices/warehouse/inventory/src:/usr/src/app/src
    networks:
      - shared-warehouses
    depends_on:
      - mongo
      - nats
      - resgate

  orders:
    build:
      context: ./microservices/warehouse/orders
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - WAREHOUSE_ID=1
    volumes:
      - ./microservices/warehouse/orders/src:/usr/src/app/src
    networks:
      - shared-warehouses
    depends_on:
      - nats    

#==========================================================================#
#                         Cloud Microservices                              #
#==========================================================================#

  inventory-aggregated:
    build:
      context: ./microservices/cloud/inventory-aggregated
      dockerfile: Dockerfile
    container_name: inventory-aggregated-1
    environment:
      - MONGO_URI=mongodb://mongo:27017/inventory-aggregated
      - NATS_URL=nats://nats:4222
    volumes:
      - ./microservices/cloud/inventory-aggregated/src:/usr/src/app/src
    networks:
      - shared-warehouses
    depends_on:
      - mongo
      - nats
      - resgate

#==========================================================================#
#                 Centralized System Microservices                         #
#==========================================================================#

  authentication:
    container_name: authentication
    build:
      context: ./microservices/centralized/authentication
      dockerfile: Dockerfile
    environment:
      - MONGO_DB=mongodb://mongo:27017/authentication
      - JWT_SECRET=IREALLYLOVEM31!!!!!!!!!!!!!!!!!!
    volumes:
      - ./microservices/centralized/authentication/src:/usr/src/app/src
    networks:
      - shared-warehouses
    depends_on:
      - nats
      - mongodb
      - resgate

  centralsystem:
    container_name: CentralSystem
    build:
        context: ./microservices/centralized/CentralSystem
        dockerfile: Dockerfile
    environment:
        - MONGO_DB=mongodb://mongo:27017/centralsystem
    volumes:
        - ./microservices/centralized/CentralSystem/src:/usr/src/app/src
    networks:
        - shared-warehouses
    depends_on:
        - nats

#==========================================================================#
#                         Infrastructure Microservices                     #
#==========================================================================#

  resgate:
    image: resgateio/resgate
    container_name: resgate
    ports:
      - "8080:8080"
    depends_on:
      - nats
    #volumes:
    #  - ./microservizi/resgate/resgate-config.json:/app/config.json
    command: 
      - "-n"
      - "nats://nats:4222"
      - "-DV"
      - "--headauth"
      - "auth.jwtHeader"
    networks:
      - shared-warehouses

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - shared-warehouses
    #volumes:
    #  - ./microservizi/mongo_db:/docker-entrypoint-initdb.d

  nats:
     container_name: nats
     image: nats:latest
     ports:
       - "4222:4222"
     command:
       - "--jetstream"
       - "--debug"
       - "--trace"
     networks:
       - shared-warehouses

networks:
  shared-warehouses:
    driver: bridge