global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "orders-aggregated"
    static_configs:
      - targets:
          - orders-aggregated:3010
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "authentication"
    static_configs:
      - targets:
          - authentication:3510
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s
