{
 "title": "Shared Warehouses",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "LoginFalliti/Minuto",
   "type": "stat",
   "description": "Per ogni minuto controlliamo i login falliti",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(login_attempts_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prodotti nei Magazzini",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 9, "y": 0 },
   "targets": [
    { "expr": "inventory_products_total", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Ordini/Minuto",
   "type": "gauge",
   "description": "Ordini inseriti al minuto per magazzino",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Ord/Min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(inserted_orders_gauge[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prodotti nei Magazzini",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "sum by(warehouse) (inventory_products_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}